#version 450
#extension GL_ARB_compute_shader : enable
#extension GL_ARB_separate_shader_objects : enable

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 0, binding = 0, r16f) uniform writeonly image2D outAO;

layout(set = 0, binding = 1) uniform sampler2D tAO;
layout(set = 0, binding = 2) uniform sampler2D tNormal;
layout(set = 0, binding = 3) uniform sampler2D tDepth;

layout(push_constant) uniform PushConstants {
    uint width;
    uint height;
    int radius;
    float sigma;
    float depthSigma;
    float normalSigma;
} pc;

float gaussian(float x, float sigma)
{
    return exp(-(x * x) / (2.0 * sigma * sigma));// / (sqrt(2.0 * 3.14159265359) * sigma);
}

void main()
{
    ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
    if (gid.x >= pc.width || gid.y >= pc.height) return;
    vec2 uv = (vec2(gid) + vec2(0.5)) / vec2(pc.width, pc.height);

    float centerAo = texture(tAO, uv).r;
    float centerDepth = texture(tDepth, uv).r;
    vec3 centerNormal = texture(tNormal, uv).xyz;

    float sum = 0.0;
    float weightSum = 0.0;

    for (uint i = -pc.radius; i < pc.radius; ++i)
    {
        ivec2 s = gid + ivec2(i, 0);
        if (s.x < 0 || s.x >= pc.width) continue;
        vec2 suv = (vec2(s) + vec2(0.5)) / vec2(pc.width, pc.height);

        float sampleAo = texture(tAO, suv).r;
        float sampleDepth = texture(tDepth, suv).r;
        vec3 sampleNormal = texture(tNormal, suv).xyz;

        float spatial =gaussian(float(i), pc.sigma);
        float depthDiff = abs(sampleDepth - centerDepth);
        float depthWeight = exp(-(depthDiff * depthDiff) / (2.0 * pc.depthSigma * pc.depthSigma));
        float nDot = max(dot(centerNormal, sampleNormal), 0.0);
        float normalWeight = exp(-((1.0 - nDot) * (1.0 - nDot)) / (2.0 * pc.normalSigma * pc.normalSigma));

        float w =spatial * depthWeight * normalWeight;
        sum += sampleAo * w;
        weightSum += w;
    }

    float outval = (weightSum > 0.0) ? sum/weightSum : centerAo;
    imageStore(outAO, gid, vec4(outval, 0.0, 0.0, 0.0));
}