#version 450

// binding = 0, set = 0
layout(set = 0, binding = 0, rgba8) uniform writeonly image2D outImage;

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

void main()
{
    ivec2 pix = ivec2(gl_GlobalInvocationID.xy);

    vec2 uv = (vec2(pix) + 0.5) / vec2(1024.0, 768.0);// 仅为示例：若 screen size 不同，图案会拉伸

    vec3 col = vec3(fract(uv.x * 6.0), fract(uv.y * 4.0), fract((uv.x + uv.y) * 3.0));

    col = sqrt(col);// gamma-ish tweak for nicer preview

    imageStore(outImage, pix, vec4(col, 1.0));
}