#version 450

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(std140, binding = 0) uniform lightParms{
    vec2 viewport;
    int tonemap;
    int enableExplosure;
    vec3 sunDir;
    float sunIntensity;
    vec3 sunColor;
    float sunAngularRadius;
    float sunGlowSpread;
    float explosure;
    int ACESFit;
    int simpleACESFit;
} lightParm;

layout (set = 0, binding = 1, rgba16f) uniform writeonly image2D outImage;
layout (set = 0, binding = 2) uniform sampler2D texAlbedo;

mat3 ACESInputMat = mat3
(
vec3(0.59719, 0.35458, 0.04823),
vec3(0.07600, 0.90834, 0.01566),
vec3(0.02840, 0.13383, 0.83777));

mat3 ACESOutputMat = mat3
(
vec3(1.60475, -0.53108, -0.07367),
vec3(-0.10208, 1.10813, -0.00605),
vec3(-0.00327, -0.07276, 1.07602));

vec3 RRTAndODTFit(vec3 v) {
    vec3 a = v * (v + 0.0245786) - 0.000090537;
    vec3 b = v * (0.983729 * v + 0.4329510) + 0.238081;
    return a / b;
}

vec3 ACESFitted(vec3 color) {
    color = color * ACESInputMat;

    // Apply RRT and ODT
    color = RRTAndODTFit(color);

    color = color * ACESOutputMat;

    // Clamp to [0, 1]
    color = clamp(color, 0.0, 1.0);

    return color;
}

vec3 ACES(in vec3 c) {
    float a = 2.51;
    float b = 0.03;
    float y = 2.43;
    float d = 0.59;
    float e = 0.14;

    return clamp((c * (a * c + b)) / (c * (y * c + d) + e), 0.0, 1.0);
}

float Luminance(vec3 c) {
    return 0.212671 * c.x + 0.715160 * c.y + 0.072169 * c.z;
}

vec3 Tonemap(in vec3 c, float limit) {
    return c * 1.0 / (1.0 + Luminance(c) / limit);
}

void main()
{
    ivec2 pix = ivec2(gl_GlobalInvocationID.xy);
    ivec2 vp = ivec2(int(lightParm.viewport.x), int(lightParm.viewport.y));
    if (pix.x >= vp.x || pix.y >= vp.y) {
        return;
    }

    vec2 uv = (vec2(pix) + 0.5) / lightParm.viewport;

    vec4 alb = texture(texAlbedo, uv);
    vec3 color = alb.rgb;

    if (lightParm.enableExplosure >= 0) {
        color = color * lightParm.explosure;
    }

    if (lightParm.tonemap > 0)
    {
        if (lightParm.ACESFit > 0) {
            if (lightParm.simpleACESFit > 0) {
                color = ACES(color);
            } else {
                color = ACESFitted(color);
            }
        }
        else {
            color = Tonemap(color, 1.5);
        }
    }

    color = pow(color, vec3(1.0 / 2.2));// gamma correction

    imageStore(outImage, pix, vec4(color, 1.0));
}